### ISSUE TITLE
No Name or Schedule props in ImagePipelineProps

### ISSUE THREAD

**Issue by masterj1337** [aws-samples/cdk-image-pipeline#253]
ImagePipelineProps doesn't contain name property for the name of the pipeline, or the ability to schedule. The issue is the pipeline ends up with a really long nonsense name for the end users and the inability to have this constantly update for automated patching.

```YAML
ArcGISProWin2022ImagePipelineA34351BC:
    Type: AWS::ImageBuilder::ImagePipeline
    Properties:
      Description: A sample image pipeline
      ImageRecipeArn:
        Fn::GetAtt:
          - ArcGISProWin2022ImageRecipe50C4B6A8
          - Arn
      InfrastructureConfigurationArn:
        Fn::GetAtt:
          - ArcGISProWin2022InfrastructureConfigurationE4944C6F
          - Arn
      Name: ImageBuilderStackArcGISProWin2022AE444C4FImagePipeline
    Metadata:
      aws:cdk:path: ImageBuilderStack/ArcGISPro-Win2022/ImagePipeline
```

```YAML
Name: ImageBuilderStackArcGISProWin2022AE444C4FImagePipeline
```

Reference ImagePipelineProps from CDK Documentation:
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_imagebuilder.CfnImagePipelineProps.html

It appears that ImagePipelineProps for this module contains what would be under ImageRecipeProps and ComponentProps from the docs.
